### ISSUE TITLE
The build is too dependent on the order of the objects passed to the linker.

### ISSUE THREAD

**Issue by minneelyyyy** [AptRock327/RaidouOS#2]
This is bad design practice and will make extending the kernel more annoying in the future. instead of requiring position dependent objects to be linked first, make a segment such as `.boot` and tell the linker to put that first.

**Comment by AptRock327** [comment]
I have experimentally changed the order of objects in linker.ld in multiple ways and have not encountered this issue. Can you list any specific example? This is strange.

**Comment by AptRock327** [comment]
Thanks for fixing that lol
